#!/usr/bin/env python3

import json
import sys

if len(sys.argv) != 2:
    print("usage: ook-remote FILE.ook")
    sys.exit(1)

# Everything before the first empty line is the json header.
# Everything after the first empty line is the data to transmit.
header_str = ""
data = []
reading_header = True
with open(sys.argv[1]) as ook_file:
    for line in ook_file:
        line = line.strip()
        if reading_header:
            if line == "":
                reading_header = False
                continue
            header_str += line
        else:
            if line == "":
                continue
            data.append(line)

header = json.loads(header_str)

with open('/dev/ttyACM0', 'w') as serial:
    if 'us-per-bit' in header:
        print(f'us-per-bit{header["us-per-bit"]}', file=serial)

    for line in data:
        print(f'tx{line}', file=serial)
