#!/usr/bin/env python3

import argparse
import json


parser = argparse.ArgumentParser(description="On/Off Keying Remote CLI")
parser.add_argument('--device', '-d', default="/dev/ttyACM0", help="Serial port connected to the ook-remote device.")
parser.add_argument("OOK_FILE", help="OOK data file to send.")

args = parser.parse_args()

# Everything before the first empty line is the json header.
# Everything after the first empty line is the data to transmit.
header_str = ""
data = []
reading_header = True
with open(args.OOK_FILE) as ook_file:
    for line in ook_file:
        line = line.strip()
        if reading_header:
            if line == "":
                reading_header = False
                continue
            header_str += line
        else:
            if line == "":
                continue
            data.append(line)

header = json.loads(header_str)

with open(args.device, 'w') as serial:
    if 'us-per-bit' in header:
        print(f'us-per-bit{header["us-per-bit"]}', file=serial)

    for line in data:
        print(f'tx{line}', file=serial)
