#!/usr/bin/env python3
import sys

if len(sys.argv) != 2:
    print("usage: ook-remote FILE.ook")
    sys.exit(1)

with open(sys.argv[1]) as ook:
    lines = ook.readlines()

with open('/dev/ttyACM0', 'w') as serial:
    for line in lines:
        line = line.strip()
        if line == "":
            continue
        print(f'tx{line}', file=serial)
